# -*- coding: utf-8 -*-
"""bianca

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AuBWh5hk-gclrwSLjH04DVmEb8uBcOuG
"""

from sklearn import tree

#Database: Gerbang logika AND
#x = Data, Y = Target
x = [[0,3], [1,3], [1,0], [2,1], [2,0], [3,6], [6,3], [4,5], [5,4], [3,3]]
y = [0,2,0,3,1,0,4,2,0,1]

#Training and Classify 
clf = tree.DecisionTreeClassifier()
clf = clf.fit(x, y)

#Prediksi
print ("Logika AND Matode Desicion Tree")
print ("Logika = Prediksi")
print ("0 3 =", clf.predict([[0,3]]))
print ("1 3 =", clf.predict([[1,3]]))
print ("1 0 =", clf.predict([[1,0]]))
print ("2 1 =", clf.predict([[2,1]]))
print ("2 0 =", clf.predict([[2,0]]))
print ("3 6 =", clf.predict([[3,6]]))
print ("6 3 =", clf.predict([[6,3]]))
print ("4 5 =", clf.predict([[4,5]]))
print ("5 4 =", clf.predict([[5,4]]))
print ("3 3 =", clf.predict([[3,3]]))